import type { Metadata } from "next";
import "./globals.css";
import NextAuthSession from "./NextAuthSession";
import { inter } from "./fonts";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css" rel="stylesheet" />
      </head>
      <body
        className={`${inter.className} antialiased`}
      >
        <NextAuthSession>
          <section className="min-h-screen">
            <Header />
              {children}
            <Footer />
          </section>
        </NextAuthSession>
      </body>
    </html>
  );
}
